name: Generate Pac-Man Contributions

on:
  schedule:
    - cron: "0 */12 * * *" # every 12 hours
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true  # <-- force Node 24
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Generate Pac-Man Contribution Graph
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: mohanad01bits

      - name: Commit and Push Graph
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Update Pac-Man contribution graph"
